name: module3_task0
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task0:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: cd into directory
        run: |
          cd module3_task0
          make help
