  name: module3_task1
  "on":
    push:
      branches:
        - main
    schedule:
      - cron: '0 0 * * *'
  
  jobs:
    builds:
      name: module3_task1
      runs-on: ubuntu-22.04
  
      steps:
        - uses: actions/checkout@v3
        - name: install Hugo script
          run: cd module3_task1 && ./setup.sh
        - name: Execute makefile commands
          run: |
            make help
            make build
            make run
            make stop
            make clean
          working-directory: module3_task1