---
name: release-drafter

"on":
  push:
    branches:
      - master

jobs:
  release-drafter:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate Changelog
        uses: actions/github-script@v5
        env:
          CHANGLOG_TOKEN: ${{ secrets.CHANGLOG_TOKEN }}
        with:
          script: |
            const { Octokit } = require('@octokit/rest');
            const { createChangelog } = require('github-changelog-generator');

            const octokit = new Octokit({ auth: process.env.CHANGLOG_TOKEN });
            createChangelog(octokit, context.repo.owner, context.repo.repo);

      - name: Update Release
        run: |
          gh release create 1.0.1 -F .github/release-drafter/changelog.md
          gh release upload 1.0.1 module3_task4/awesome-website.zip
          gh release upload 1.0.1 module3_task4/DEPLOY.md
